services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./sabnzdb/config:/config
      - /mnt/Download-Temp/sabnzdb/downloads:/downloads
      - /mnt/Download-Temp/sabnzdb/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
      - 9090:9090

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./sonarr:/config
      - /mnt/Media/TV:/tv
      - /mnt/Download-Temp/sabnzdb/downloads:/downloads
    ports:
      - 8989:8989

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./Radarr:/config
      - /mnt/Media/Movies:/movies #optional
      - /mnt/Download-Temp/sabnzdb/downloads:/downloads #optional
    ports:
      - 7878:7878

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./heimdall:/config
    ports:
      - 8181:80
      - 443:443

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./readarr:/config
      - /mnt/Media/Books:/books #optional
      - /mnt/Media/audiobooks:/audiobooks
      - /mnt/Download-Temp/sabnzdb/downloads:/downloads #optional
    ports:
      - 8787:8787

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - AUDIOBOOKSHELF_UID=1000
      - AUDIOBOOKSHELF_GID=1000
    ports:
      - 13378:80
    volumes:
      - /mnt/Media/audiobooks:/audiobooks
      - ./audiobookshelf:/config
      - ./audiobookshelf:/metadata
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Portainer:/data
    ports:
      - 9000:9000

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./ombi:/config
    ports:
      - 3579:3579